<div class="newstitle">
<h2>Matthew House to officially launch new Flight to Freedom program at June 11th Fundraiser</h2>
</div>
<p></p>
<p>06.04.14</p>
<div class="newsbody"><p>Background:</p>
<p>On December 15th 2012, the Canadian refugee processing system underwent significant changes resulting in much shorter timelines and tighter rules for refugees making an asylum claim in Canada.&nbsp; Newly arrived refugee claimants now face a much more challenging path preparing for their refugee hearings and the need for extra help with the process has become vital.</p>
<p>In response to this need, in early 2013, Matthew House embarked in the creation of a program to effectively assist our residents in better preparing for their claim in the very short time lines.&nbsp; &nbsp;A pilot program was established which included the development of a Refugee Hearing Preparation Tool Kit complete with power points, checklists, orientation booklets and tours to the Immigration and Refugee Board (IRB).&nbsp; An exciting element of the new program entailed holding a &ldquo;mock hearing&rdquo; exercise which is a simulation of an actual IRB hearing.&nbsp; It is usually held a few weeks in advance of a refugee&rsquo;s hearing date and enables them to familiarize themselves with the entire hearing procedure.&nbsp; The Mock Hearing exercise has met with tremendous success and has been fully implemented. Many of our residents who have had a mock hearing say that it helped significantly in preparing them for and successfully completing the real thing. &nbsp;Word is spreading and other refugee serving agencies across the country&nbsp;are interesting in&nbsp;learning more about this program.</p>
<p>As a result of the implementation of this program, which we call the<strong> Flight to Freedom program</strong>, a new staff position dedicated to helping our guests with every step of the refugee claim process, was created.&nbsp; We are pleased to welcome <strong>Samia Tecle </strong>to the Matthew House teamas our new Refugee Claim Counselor. &nbsp;</p>
<p style="text-align: center;"><img alt="" src="/site/ywd_trialsite_1564/assets/images/Samia_Tecle_photo-1.jpg" style="width: 180px; height: 266px; border-style: solid;" />&nbsp;</p>
<p>Born in Toronto to two refugees (from Eritrea) herself, Samia has always been aware of the challenges facing newly arrived refugees as they begin their new life in Canada and has a heart to make a difference for them. Samia holds a double-major Honours Bachelor degree in Political Science and International Development from York University where she graduated with special recognition for her extensive cross-cultural and international work. She also holds a Masters degree in Refugee Studies and has several years experience working in the refugee field. &nbsp;&nbsp;We are excited about the wealth of experience Samia brings to Matthew House and our Flight to Freedom program and we welcome her to our team!</p>
<p>Proceeds from our special event on June 11th ( <strong>Everybodys Children </strong>documentary)&nbsp;will go toward this new program.&nbsp; Our goal is to raise <strong>$50,000</strong>. toward the ongoing implementation of this program.&nbsp; How do we hope to accomplish this?&nbsp;&nbsp; The most effective way of ensuring long term sustainability is through ongoing monthly support.&nbsp; Nothing is more appreciated by a nonprofit charity than the assurance of regular income.&nbsp; We are therefore appealing to our supporters to consider a regular monthly gift to our work with newly arrived refugees who would otherwise be homeless in Canada.&nbsp;</p>
<p>The name <strong>Matthew House </strong>is derived from the passage in the newestament where Jesus said in Matthew 25:35 &ldquo; I was a stranger and you welcomed me&hellip;&rdquo;.&nbsp; &nbsp;As a reflection of these words, we have launched a monthly donor campaign called the &ldquo;25:35 Campaign&rdquo; which challenges potential supporters to consider giving a minimum gift of $25.35 per month toward the support of Matthew House.&nbsp;&nbsp; It is amazing how far even a small donation can go if it is multiplied many times over.&nbsp; To date, this year we have about 15 pledges toward the new program.&nbsp;&nbsp; If 150 new people signed up to give just <strong>$25.35 a month</strong>, we would reach or goal of sustaining this program well into the future!!&nbsp; It is no more than the cost of the ticket to&nbsp;our special&nbsp;event.&nbsp;&nbsp; Will you take up the 25:35 Challenge and help us welcome newly arrived homeless refugees into a safe caring community like Matthew House?</p>
<p>For more details about our special June fundraiser, click on the Butterfly icon on our Home page or the Events tab.</p></div>
<div class="contentbottomlinksgoback">
