<div class="newstitle">
<h2>Reflections from our Founder on current refugee crisis</h2>
</div>
<p></p>
<p>09.10.15</p>
<div class="newsbody"><p>Dear Friends, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>&nbsp;</p>
<p>Like many of you, my heart broke as I saw the photo of little Alan Kurdi, the young Syrian-Kurdish boy who drowned in the Aegean Sea recently.</p>
<p>His story brought to my mind a similar story that touched me so deeply more than 25 years ago that it inspired me to respond to the plight of refugees &ndash; and ultimately establish Matthew House.&nbsp; At that time I had met a young Vietnamese man who shared his heart wrenching story of fleeing from his homeland and languishing in a small boat at sea enduring horrific hardship &ndash; even losing a brother and sister to starvation.&nbsp; To this day I am moved when I recall his account but what touched and shocked me the most about his story was his description of his experience upon arrival in Canada.&nbsp; He described it as the most difficult and painful part of his whole journey!&nbsp; Why? Because during his early days, no one truly welcomed him. &nbsp;He felt alone and afraid.&nbsp; He confessed to me that he used to cry himself to sleep at night here in Canada!&nbsp; My heart broke when I heard this story and I wanted to respond - to help make refugees like him feel more welcome here in Canada. I began to volunteer at a refugee agency and&hellip; the rest is history. &nbsp;</p>
<p>Fast forward 28 years to last Thursday night where, while at small rally of faithful refugee advocates, I met a young man who was a newly arrived refugee from Syria - just 3 months in Canada. When I asked how he was adjusting to life in Canada, he confessed that while he was grateful to be alive and safe, he was now facing new very significant struggles here &ndash; more than he had anticipated.&nbsp; He reminded me of my original refugee friend years ago and his grappling for a real sense of belonging in Canada.&nbsp; I told him he was welcome to visit Matthew House and he gladly accepted the invitation.</p>
<p>I know that what he will find at Matthew House is a caring community that warmly welcomes and embraces people from all walks of life, nationalities and backgrounds and helps them not only with practical refugee settlement support but offers a real sense of community and&nbsp; belonging.</p>
<p>The recent refugee crisis in Europe has caused people to be asking us <strong>&ldquo;What can we do to help refugees?&rdquo;</strong></p>
<p>The answer? <strong>&nbsp;You can help us keep our doors open as a safe haven&nbsp;for refugees!</strong></p>
<p>To be very honest, Matthew House is currently facing the greatest financial challenge in our history as a refugee ministry.&nbsp; At present we are<strong> more than $100,000 </strong>behind in donations this year and in addition, one of our transition homes has a significant maintenance issue which could entail <strong>more than $50,000 </strong>in repair work in order to ensure that the affected apartment (from which we have had to remove an Eritrean mother and baby) is fit to live in again.&nbsp; As a charity that receives no direct government funding, we are truly dependent on private donors like you to keep our doors open.</p>
<p>You can help in the following ways:</p>
<ul>
<li>Give a direct financial gift today by<a href="https://www.canadahelps.org/en/charities/matthew-house-refugee-reception-services-toronto/"> donating now</a>.&nbsp;&nbsp;&nbsp;&nbsp;</li>
<li><a href="index969d.html?eventid=8256&amp;pagepath=Events&amp;id=49964#event8256">Join our Scotiabank Charity Run Team</a> ( 5km/ half and full marathon) on October 18th and walk or run for a refugee.&nbsp;</li>
<li>Share about the work of Matthew House and our needs among your friends who are wanting to respond to the plight of refugees.</li>
</ul>
<p>Since opening in 1998 we have been quietly responding with open arms and compassion to hundreds of asylum seekers who have been &ldquo;washing up on our shores&rdquo; irrespective of whether refugees are in the media spotlight or not. &nbsp;We have provided a place of welcome and community for those who have no one in Canada. Our track record speaks for itself.&nbsp; There is no system in place to help them here and they are simply numbered among the homeless knowing no one nor where to turn for help.&nbsp;&nbsp; Some spend their initial days in Canada homeless on the street or at very rough hostels where they are retraumatized.</p>
<p>Will you partner with us in support of our work of welcoming those refugee claimants who manage to reach our country?&nbsp;</p>
<p>Just in the last few days alone, we have received four unaccompanied minor refugee teens: two young girls from Eritrea and two boys from Afghanistan.&nbsp; None have parents or any family in Canada.&nbsp; For each of them, Matthew House has become their family.&nbsp; Thanks to your support, we will be able to provide not only shelter and help with their refugee claim process but also the opportunity to live long term at one of our transition homes where they can complete high school in a supportive family-like environment. &nbsp;And we already have a legacy of successfully sending many such teens on to university!</p>
<p>Thank you for considering my appeal for support.&nbsp; You can rest assured that your gift will tangibly touch the lives of refugees in desperate need.&nbsp; &nbsp;And you don&rsquo;t have to wait for years to meet the refugees you are supporting &ndash; you can visit one of our homes today and meet them face to face and see for yourself how your gift is changing lives. &nbsp;</p>
<p>And finally, may I ask one more favour?&nbsp; As the refugee issue is in the forefront today and your friends or family may also be wondering how they might respond to the plight of refugees in a meaningful way, would you be kind enough to share with them about Matthew House by sending them links to information about Matthew House. &nbsp;Your personal endorsement of our work can go a long way to helping us meet our needs. &nbsp;</p>
<p>In closing, thank you again for partnering with us in bringing love and hope to those at the end of their long journey on the refugee highway.</p>
<p>Anne Woolger</p>
<p>&nbsp;</p>
<p>Founder</p>
<p>Matthew House Refugee Reception Services, Toronto</p>
<p>&nbsp;</p>
<p>PS: This is my first &ldquo;Founder&rsquo;s Blog&rdquo;.&nbsp; Stay tuned for more blogs providing reflections and updates on how you can effectively support refugees.</p></div>
<div class="contentbottomlinksgoback">
